api_platform:
    title: 'OLY BE - GPS Search'
    description: 'Checking coordonates & persisting data'
    version: '1.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
